# Generated by Django 2.0.9 on 2018-11-24 16:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='M', max_length=1)),
                ('notes', models.TextField(blank=True)),
                ('vrc', models.BooleanField(default=False)),
                ('bureau_states', models.ManyToManyField(related_name='employees', related_query_name='employee', to='cities_light.Region')),
            ],
        ),
        migrations.CreateModel(
            name='Regiment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.IntegerField(blank=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('us', models.BooleanField(default=False)),
                ('usct', models.BooleanField(default=False)),
                ('vrc', models.BooleanField(default=False)),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.Region')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='vrc_units',
            field=models.ManyToManyField(related_name='employees', related_query_name='employee', to='personnel.Regiment'),
        ),
    ]
