# Generated by Django 2.0.9 on 2018-11-24 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='bureau_states',
        ),
        migrations.RemoveField(
            model_name='regiment',
            name='state',
        ),
    ]
