# Generated by Django 2.0.9 on 2018-11-24 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
        ('personnel', '0002_auto_20181124_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bureau_states',
            field=models.ManyToManyField(related_name='employees', related_query_name='employee', to='places.Region'),
        ),
        migrations.AddField(
            model_name='regiment',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.Region'),
        ),
    ]
