# Generated by Django 2.0.9 on 2018-11-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_auto_20181124_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='bureau_states',
            field=models.ManyToManyField(limit_choices_to={'bureau_operations': True}, related_name='employees', related_query_name='employee', to='places.Region'),
        ),
    ]
