# Generated by Django 2.0.9 on 2018-11-25 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0004_auto_20181124_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regiment',
            name='state',
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='vrc_units',
        ),
        migrations.DeleteModel(
            name='Regiment',
        ),
    ]
