# Generated by Django 2.0.9 on 2018-11-25 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0006_employee_vrc_units'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='vrc_units',
            new_name='regiments',
        ),
    ]
