# Generated by Django 2.0.9 on 2019-01-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0009_employee_ailments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='bureau_states',
            field=models.ManyToManyField(blank=True, limit_choices_to={'bureau_operations': True}, related_name='employees_employed', related_query_name='employee_employed', to='places.Region'),
        ),
    ]
