# Generated by Django 2.2.9 on 2021-01-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0012_auto_20190421_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='confederate',
            new_name='confederate_veteran',
        ),
        migrations.AddField(
            model_name='employee',
            name='union_veteran',
            field=models.BooleanField(default=False),
        ),
    ]
