# Generated by Django 4.0.10 on 2023-10-17 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_auto_20220209_1727'),
        ('personnel', '0013_auto_20210116_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='bureau_states',
            field=models.ManyToManyField(blank=True, limit_choices_to={'bureau_operations': True}, related_name='employees_employed', related_query_name='employee_employed', to='places.region', verbose_name='bureau states (location)'),
        ),
    ]
