language: python
#python:
#  "3.6"
#
## command to install dependencies
#install:
#  - pip install -r requirements/local.txt
#
## command to run tests
#script:
#  - python manage.py test

services:
  - docker

before_install:
  - docker build compose/local/django .
  - docker ps -a

script:
  - docker-compose -f local.yml up django run manage.py test
