# Generated by Django 2.0.9 on 2018-11-25 02:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regiment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.IntegerField(blank=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('us', models.BooleanField(default=False)),
                ('usct', models.BooleanField(default=False)),
                ('vrc', models.BooleanField(default=False)),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.Region')),
            ],
            options={
                'ordering': ['state', 'vrc', 'us', 'usct', 'number', 'name'],
            },
        ),
    ]
