# Generated by Django 2.0.9 on 2019-01-08 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('military', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regiment',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
