# Generated by Django 2.2.9 on 2021-01-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('military', '0003_regiment_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='regiment',
            name='confederate',
            field=models.BooleanField(default=False),
        ),
    ]
