# Generated by Django 2.2.9 on 2021-01-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('military', '0004_regiment_confederate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regiment',
            name='branch',
            field=models.CharField(choices=[('INF', 'Infantry'), ('CAV', 'Cavalry'), ('ART', 'Artillery'), ('SHA', 'Sharpshooters')], default='INF', max_length=3),
        ),
    ]
