# Generated by Django 2.2.9 on 2021-01-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('military', '0005_auto_20210116_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regiment',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
