# Generated by Django 2.2.9 on 2021-01-20 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('military', '0006_auto_20210116_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regiment',
            name='branch',
            field=models.CharField(choices=[('INF', 'Infantry'), ('CAV', 'Cavalry'), ('ART', 'Artillery'), ('ENG', 'Engineers'), ('SHA', 'Sharpshooters')], default='INF', max_length=3),
        ),
    ]
