# Generated by Django 2.0.9 on 2019-04-24 10:59

from django.db import migrations, models
import django.db.models.deletion
import partial_date.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnel', '0012_auto_20190421_1939'),
        ('places', '0003_auto_20190423_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', partial_date.fields.PartialDateField(blank=True, null=True)),
                ('end_date', partial_date.fields.PartialDateField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='personnel.Employee')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='places.Place')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='assignments.Position'),
        ),
    ]
