# Generated by Django 2.0.9 on 2019-04-27 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20190425_1053'),
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='place',
        ),
        migrations.AddField(
            model_name='assignment',
            name='place',
            field=models.ManyToManyField(blank=True, limit_choices_to={'region__bureau_operations': True}, related_name='assignments', related_query_name='assignment', to='places.Place'),
        ),
    ]
