# Generated by Django 2.0.9 on 2019-04-27 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_auto_20190427_0306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='place',
            new_name='places',
        ),
    ]
