# Generated by Django 2.0.9 on 2019-04-27 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_auto_20190427_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='description',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
