# Generated by Django 2.0.9 on 2019-07-08 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_assignment_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['title']},
        ),
    ]
