# Generated by Django 2.0.9 on 2019-07-20 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_auto_20190708_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='positions',
            field=models.ManyToManyField(blank=True, related_name='assignments', related_query_name='assignment', to='assignments.Position'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments_old', to='assignments.Position'),
        ),
        migrations.AlterField(
            model_name='position',
            name='title',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
