# Generated by Django 2.0.9 on 2019-07-20 14:08

from django.db import migrations

def copy_assignment_position_to_positions(apps, schema_editor):
    # We can't import the Assignment model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Assignment = apps.get_model('assignments', 'Assignment')
    for assignment in Assignment.objects.all():
        if assignment.position:
            assignment.positions.add(assignment.position)


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_auto_20190720_1408'),
    ]

    operations = [
        migrations.RunPython(copy_assignment_position_to_positions, reverse_code=migrations.RunPython.noop),
    ]
