# Generated by Django 2.0.9 on 2019-07-20 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0007_auto_20190720_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='position',
        ),
    ]
