# Generated by Django 2.2.9 on 2021-09-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0008_remove_assignment_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='bureau_headquarters',
            field=models.BooleanField(default=False),
        ),
    ]
