# Generated by Django 3.2.13 on 2022-08-19 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_auto_20220209_1727'),
        ('assignments', '0009_assignment_bureau_headquarters'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='bureau_state',
            field=models.ForeignKey(blank=True, limit_choices_to={'bureau_operations': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='places.region'),
        ),
    ]
