# Generated by Django 3.2.13 on 2022-08-19 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_auto_20220209_1727'),
        ('assignments', '0010_assignment_bureau_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='bureau_states',
            field=models.ManyToManyField(blank=True, limit_choices_to={'bureau_operations': True}, related_name='assignments', related_query_name='assignment', to='places.Region'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='bureau_state',
            field=models.ForeignKey(blank=True, limit_choices_to={'bureau_operations': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bureau_state_assignments', to='places.region'),
        ),
    ]
