# Generated by Django 3.2.13 on 2022-08-19 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0011_auto_20220819_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='bureau_state',
        ),
    ]
