version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    working_directory: ~/bureau
    docker:
      - image: circleci/python:3.6.4 # every job must define an image for the docker executor and subsequent jobs may define a different image.
        environment:
          DATABASE_URL: postgres://postgres@localhost/test_db
          USE_DOCKER: no
      - image: circleci/postgres:9.6.2 # an example of how to specify a service container
        environment:
          POSTGRES_DB: test_db
    steps:
    - checkout  # checkout source code to working directory
    - run: sudo chown -R circleci:circleci /usr/local/bin
    - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
    - run:
        command: |  # use pipenv to install dependencies
          sudo pip install -r requirements/local.txt
    - run:
        command: |
          python manage.py test
    - run:
        command: |
          coverage run manage.py test
    - codecov/upload:
        file: {{ coverage_report_filepath }}




