version: 2.1
jobs:
  build:
    working_directory: ~/bureau
    docker:
      - image: cimg/python:3.11.1
        environment:
          DATABASE_URL: postgres://postgres@localhost/test_db
          USE_DOCKER: no
      - image: cimg/postgres:14.1
        environment:
          POSTGRES_DB: test_db
    steps:
    - checkout  # checkout source code to working directory
    - run:
        command: |
          sudo chown -R circleci:circleci /usr/local/bin
          sudo chown -R circleci:circleci /home/circleci/.pyenv/versions/3.11.1/lib/python3.11/site-packages
    - restore_cache: # restore cached dependencies
        key: pip-env-{{ checksum "requirements/local.txt" }}
    - run:
        name: 'Install dependencies'
        command: |
          pip install -r requirements/local.txt
          pip install coveralls
    - save_cache: # cache installed dependencies
        key: pip-env-{{ checksum "requirements/local.txt" }}
        paths:
          - '/home/circleci/.cache/pip'
          - '/usr/local/bin'
          - '/home/circleci/.pyenv/versions/3.11.1/lib/python3.11/site-packages'
    - run:
        name: 'Linters'
        command: |
          python3 -m flake8
          pwd
          python3 -m pylint bureau
    - run:
        name: 'Tests'
        command: |
          python3 -m coverage run manage.py test
    - run:
        name: 'Coveralls'
        command: |
          python3 -m coveralls
