version: 2.1
jobs:
  build:
    working_directory: ~/bureau
    docker:
      - image: circleci/python:3.6.4 # every job must define an image for the docker executor and subsequent jobs may define a different image.
        environment:
          DATABASE_URL: postgres://postgres@localhost/test_db
          USE_DOCKER: no
      - image: circleci/postgres:9.6.2 # an example of how to specify a service container
        environment:
          POSTGRES_DB: test_db
    steps:
    - checkout  # checkout source code to working directory
    - run: sudo chown -R circleci:circleci /usr/local/bin
    - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
    - restore_cache: # restore cached dependencies
        key: pip-env-{{ checksum "requirements.txt" }}
    - run:
        command: |  # install dependencies
          sudo pip install -r requirements/local.txt
          sudo pip install coveralls
    - save_cache: # cache installed dependencies
        key: pip-env-{{ checksum "requirements.txt" }}
        paths:
          - ".cache/pip"
          - '/usr/local/bin'
          - '/usr/local/lib/python3.6/site-packages'
    - run:
        command: |
          coverage run manage.py test
    - run:
       command: |
          coveralls



