version: 2
jobs:
  build:
    working_directory: ~/bureau
    docker:
      - image: circleci/python:3.6.4 # every job must define an image for the docker executor and subsequent jobs may define a different image.
        environment:
          DATABASE_URL: postgres://postgres@localhost/test_db
          USE_DOCKER: no
      - image: circleci/postgres:9.6.2 # an example of how to specify a service container
        environment:
          POSTGRES_DB: test_db
    steps:
    - checkout  # checkout source code to working directory
    - run:
        command: |  # use pipenv to install dependencies
          sudo pip install pipenv
          pipenv install

