version: 2.1
jobs:
  build:
    working_directory: ~/bureau
    docker:
      - image: cimg/python:3.11.1 # every job must define an image for the docker executor and subsequent jobs may define a different image.
        environment:
          DATABASE_URL: postgres://postgres@localhost/test_db
          USE_DOCKER: no
      - image: cimg/postgres:14.1
        environment:
          POSTGRES_DB: test_db
    steps:
    - checkout  # checkout source code to working directory
    - run: sudo chown -R circleci:circleci /usr/local/bin
    - run:
        command: |
          which python3
          python -c 'import site; print(site.getsitepackages())'
    - run: sudo chown -R circleci:circleci /home/circleci/.pyenv/versions/3.11.1/lib/python3.11/site-packages
    - restore_cache: # restore cached dependencies
        key: pip-env-{{ checksum "requirements/local.txt" }}
    - run:
        command: |  # install dependencies
          pip install -r requirements/local.txt
          pip install coveralls
    - save_cache: # cache installed dependencies
        key: pip-env-{{ checksum "requirements/local.txt" }}
        paths:
          - '/home/circleci/.cache/pip'
          - '/usr/local/bin'
          - '/home/circleci/.pyenv/versions/3.11.1/lib/python3.11/site-packages'
    - run:
        command: |
          /home/circleci/.pyenv/versions/3.11.1/bin/python3.11 -m coverage run manage.py test
    - run:
       command: |
          /home/circleci/.pyenv/versions/3.11.1/bin/python3.11 -m coveralls
