version: 2
jobs:
  build:
    working_directory: ~/bureau
    docker:
      - image: circleci/python:3.6.4 # every job must define an image for the docker executor and subsequent jobs may define a different image.
        environment:
          DATABASE_URL: postgres://postgres@localhost/test_db
          USE_DOCKER: no
      - image: circleci/postgres:9.6.2 # an example of how to specify a service container
        environment:
          POSTGRES_DB: test_db
    steps:
    - checkout  # checkout source code to working directory
    - run: sudo chown -R circleci:circleci /usr/local/bin
    - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
#    - restore_cache:  # ensure this step occurs *before* installing dependencies
#        key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
    - run:
        command: |  # use pipenv to install dependencies
          sudo pip install pipenv
#          pipenv install
          sudo pip install -r requirements/local.txt
#    - save_cache:
#        key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
#        paths:
#          - ".venv"
#          - "/usr/local/bin"
#          - "/usr/local/lib/python3.6/site-packages"
    - run:
        command: |
          python manage.py test
       #          pipenv run "python manage.py test"
    - store_test_results:
        path: test-results
    - store_artifacts:
        path: test-results
        destination: tr1



