# States/areas where Freedmen's Bureau carried out operations,
# including what is now Oklahoma (then called Indian Territory or Cherokee Nation)
BUREAU_STATES = [
    'AL',
    'AR',
    'DC',
    'DE',
    'FL',
    'GA',
    'IL',
    'KS',
    'KY',
    'LA',
    'MD',
    'MS',
    'MO',
    'NC',
    'OK',
    'SC',
    'TN',
    'TX',
    'VA',
    'WV',
]
