# Generated by Django 2.0.9 on 2019-07-08 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20190425_1053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={},
        ),
    ]
